### ISSUE TITLE
Error when unauthorized user viewing a Colearning Space

### ISSUE THREAD

**Issue by mustafacagataytulun** [mustafacagataytulun/bounswe573-2022#53]
Anonymous users cannot view inside colearning spaces and get error.

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/spaces/14/articles

Django Version: 4.0.4
Python Version: 3.8.10
Installed Applications:
['articles',
 'dashboard',
 'glossary',
 'spaces',
 'users',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_bootstrap5',
 'markdownify.apps.MarkdownifyConfig',
 'storages']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/mustafacagataytulun/code/bounswe573-2022/colearnapp/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mustafacagataytulun/code/bounswe573-2022/colearnapp/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mustafacagataytulun/code/bounswe573-2022/colearnapp/spaces/views.py", line 45, in articles
    has_user_joined = request.user.has_joined_to_space(id)
  File "/home/mustafacagataytulun/code/bounswe573-2022/colearnapp/venv/lib/python3.8/site-packages/django/utils/functional.py", line 259, in inner
    return func(self._wrapped, *args)

Exception Type: AttributeError at /spaces/14/articles
Exception Value: 'AnonymousUser' object has no attribute 'has_joined_to_space'
```

**Comment by mustafacagataytulun** [comment]
Fixed by checking if the user is authorized first.
